### ISSUE TITLE
Package plugin loader spins indefinitely

### ISSUE THREAD

**Issue by alechp** [jadjoubran/webdash-package-json#7]
* Visual:

<img width="1792" alt="screen shot 2018-03-26 at 3 52 47 pm" src="https://user-images.githubusercontent.com/3058939/37937365-34674e2e-310e-11e8-821d-837a2ec8d8f2.png">

<img width="775" alt="screen shot 2018-03-26 at 3 56 49 pm" src="https://user-images.githubusercontent.com/3058939/37937396-57c2ed9c-310e-11e8-8ad0-dd0b24613fbf.png">

* Console:
<img width="1792" alt="screen shot 2018-03-26 at 3 52 16 pm" src="https://user-images.githubusercontent.com/3058939/37937373-3a471702-310e-11e8-8d02-78475778715f.png">

**Comment by jadjoubran** [comment]
Thanks for opening an issue!
Which versions of chrome and node are you running?

**Comment by alechp** [comment]
**Chrome**
Version 62.0.3202.94 (Official Build) (64-bit)

**Node**
9.8.0

**Comment by jadjoubran** [comment]
This is most probably due to Chrome being a bit outdated
I'm surprised though that it doesn't show that you've got an update
I'm running Chrome 65, can you please check if there's an update?
I think it should fix it as `.finally` was shipped in Chrome 63 maybeThis is most probably due to Chrome being a bit outdated
I'm surprised though that it doesn't show that you've got an update
I'm running Chrome 65, can you please check if there's an update?
I think it should fix it as `.finally` was shipped in Chrome 63 maybe

**Comment by alechp** [comment]
Updating Chrome worked. Thanks @jadjoubran
